# Generated by Django 5.0.6 on 2024-06-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_alter_profile_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='relationship',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('parent', 'Parent'), ('oldstudent', 'Old Student')], default='single', max_length=100, null=True),
        ),
    ]
