# Generated by Django 5.0.6 on 2024-06-11 16:22

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
