# Generated by Django 5.0.6 on 2024-06-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_story_image_alter_story_slug_alter_story_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerscommunity',
            name='title',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
