# Generated by Django 5.0.6 on 2024-06-14 14:50

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_developerscommunity_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='followers',
        ),
        migrations.AddField(
            model_name='page',
            name='followers',
            field=models.IntegerField(blank=True, default=0, verbose_name=userauths.models.User),
        ),
    ]
