# Generated by Django 5.0.6 on 2024-06-14 15:04

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_page_followers_page_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='followers',
        ),
        migrations.AddField(
            model_name='page',
            name='followers',
            field=models.IntegerField(default=0, verbose_name=userauths.models.User),
        ),
    ]
