# Generated by Django 5.0.6 on 2024-06-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_group_memebers_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='video',
        ),
        migrations.RemoveField(
            model_name='page',
            name='video',
        ),
    ]
