# Generated by Django 5.0.6 on 2024-06-17 12:55

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_chatmessage_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='pid',
            new_name='sid',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.RemoveField(
            model_name='story',
            name='video',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=userauths.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
