# Generated by Django 5.0.6 on 2024-06-17 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_pid_story_sid_remove_post_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.story'),
        ),
    ]
