# Generated by Django 5.0.6 on 2024-06-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_gallery_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='gid',
            new_name='pid',
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('Technology', 'technology'), ('Cars and Vehicle', 'cars and vehicle'), ('Comedy ', 'comedy'), ('Economics and Trade ', 'economics and trade'), ('Education ', 'Education'), ('Entertainment ', 'entertainment'), ('Movies and Animation ', 'movies and animation'), ('Gaming ', 'gaming'), ('History and Facts ', 'history and facts'), ('LifeStyle', 'lifestyle'), ('Others ', 'others')], default='Technology', max_length=30),
        ),
    ]
